# Program to identify IP Class, Range, Default Subnet Mask,
# Number of Networks, Number of Hosts, and Binary Reasoning
ip = input("Enter an IP address: ")
first_octet = int(ip.split(".")[0])
if 1 <= first_octet <= 126:
 print("\nClass A")
 print("Range: 1.0.0.0 - 126.255.255.255")
 print("Binary Reason:")
 print(" First bit is fixed as 0")
 print(" Pattern: 0xxxxxxx")
 print("Default Subnet Mask: 255.0.0.0 (/8)")
 print("No of Networks: 2^7 - 2 = 126")
 print("Reason:")
 print(" - First bit is fixed as 0, leaving 7 bits for network IDs.")
 print(" - Therefore, Number of Networks = 2^7.")
 print(" - Subtract 2 because Network 0 is reserved and Network 127 is reserved for
Loopback.")
 print("No of Hosts: 2^24 - 2 = 16,777,214")
 print("Reason:")
 print(" - 24 bits are available for host IDs.")
 print(" - Subtract 2 because one address is the Network Address and one is the
Broadcast Address.")
elif first_octet == 127:
 print("\nLoopback Address")
 print("Range: 127.0.0.0 - 127.255.255.255")
 print("Binary: 01111111")
 print("Reason:")
 print(" - Reserved by the IPv4 standard for loopback testing.")
 print(" - Used to test the local machine.")
 print(" - Any packet sent to a 127.x.x.x address is returned to the same computer
instead of being sent over the network.")
elif 128 <= first_octet <= 191:
 print("\nClass B")
 print("Range: 128.0.0.0 - 191.255.255.255")
 print("Binary Reason:")
 print(" First two bits are fixed as 10")
 print(" Pattern: 10xxxxxx")
 print("Default Subnet Mask: 255.255.0.0 (/16)")
 print("No of Networks: 2^14 = 16,384")
 print("Reason:")
 print(" - First 2 bits are fixed as 10.")
 print(" - Remaining 6 bits in the first octet + 8 bits in the second octet = 14 network
bits.")
 print(" - Therefore, Number of Networks = 2^14.")
 print("No of Hosts: 2^16 - 2 = 65,534")
 print("Reason:")
 print(" - 16 bits are available for host IDs.")
 print(" - Subtract 2 because one address is the Network Address and one is the
Broadcast Address.")
elif 192 <= first_octet <= 223:
 print("\nClass C")
 print("Range: 192.0.0.0 - 223.255.255.255")
 print("Binary Reason:")
 print(" First three bits are fixed as 110")
 print(" Pattern: 110xxxxx")
 print("Default Subnet Mask: 255.255.255.0 (/24)")
 print("No of Networks: 2^21 = 2,097,152")
 print("Reason:")
 print(" - First 3 bits are fixed as 110.")
 print(" - Remaining 5 bits in the first octet + 8 bits in the second octet + 8 bits in the
third octet = 21 network bits.")
 print(" - Therefore, Number of Networks = 2^21.")
 print("No of Hosts: 2^8 - 2 = 254")
 print("Reason:")
 print(" - 8 bits are available for host IDs.")
 print(" - Subtract 2 because one address is the Network Address and one is the
Broadcast Address.")
elif 224 <= first_octet <= 239:
 print("\nClass D (Multicast)")
 print("Range: 224.0.0.0 - 239.255.255.255")
 print("Binary Reason:")
 print(" First four bits are fixed as 1110")
 print(" Pattern: 1110xxxx")
 print("Default Subnet Mask: Not Applicable")
 print("No of Networks: Not Applicable")
 print("No of Hosts: Not Applicable")
 print("Reason:")
 print(" - Class D addresses are reserved for multicast communication.")
 print(" - They are not assigned to individual hosts.")
elif 240 <= first_octet <= 255:
 print("\nClass E (Experimental)")
 print("Range: 240.0.0.0 - 255.255.255.255")
 print("Binary Reason:")
 print(" First four bits are fixed as 1111")
 print(" Pattern: 1111xxxx")
 print("Default Subnet Mask: Not Applicable")
 print("No of Networks: Not Applicable")
 print("No of Hosts: Not Applicable")
 print("Reason:")
 print(" - Class E addresses are reserved for experimental and research purposes.")
 print(" - They are not used for general host addressing.")
else:
 print("Invalid IP Address") 
